### ISSUE TITLE
GetSourcePaths fails if any syntax trees don't come from on-disk files

### ISSUE THREAD

**Issue by canuckotter** [xstos/apps#1]
https://github.com/xstos/apps/blob/c0b6101d92b0036e5666021c6dfefe0bd9b6106b/playground/csharp/IndexerSourceGenerator/IndexerSourceGenerator/Indexer.cs#L81

As an alternative, how about something like:

                IEnumerable<FileInfo> GetSourcePaths() =>
                    context.Compilation.SyntaxTrees
                        .Where(st => !string.IsNullOrWhiteSpace(st.FilePath))
                        .Select(st => new FileInfo(st.FilePath));

This can happen if the source generator added extra syntax trees earlier in the process... In practice, unlikely to be an issue for this particular generator but still, better safe than sorry.

**Comment by xstos** [comment]
Good call thx. Just added.
